spring.application.name=ExpenseTrackerApplication

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true